### ISSUE TITLE
生成的二维码图片jsqr库无法解析

### ISSUE THREAD

**Issue by JohnnyYeen** [latentcat/qrbtf#28]
使用该项目的二维码图片，用jsQR库无法将二维码图片读取出正确信息。
我试了一下网上找的其他二维码图片，jsQR均可正常解析。

https://github.com/cozmo/jsQR

**Comment by CPunisher** [comment]
仅确保主流的二维码扫描工具（微信、QQ、支付宝等）能够正确识别。
看了下这个库的issue发现也有大量的无法识别问题。。。
