### ISSUE TITLE
Plans to Open Source the AI Version?

### ISSUE THREAD

**Issue by Gspohu** [latentcat/qrbtf#61]
Hello, I've been exploring the "qrbtf" website and am quite impressed with its capabilities with AI. Are there any plans to open source this AI version in a repository? It would be fantastic to see and potentially contribute to such an advancement.

Thank you for your great work on the project.

**Comment by ciaochaos** [comment]
There are too many people taking advantage of our past open source model to make money, so we do not plan to open source this QR code ControlNet for the time being. Thanks for understanding.
