### ISSUE TITLE
请问项目方的下载二维码是入如何做的 是调用接口 后端统一返回图片吗

### ISSUE THREAD

**Issue by Xujalg** [latentcat/qrbtf#67]

**Comment by phuqn10x** [comment]
我认为这是一个按顺序运行的api（可以运行ReadableStream），因此它们可以输出正在形成的AI图像的过程

**Comment by CPunisher** [comment]
对于 AI 二维码，后端返回了图片地址
对于普通二维码，可以将数据转化为 base64 后通过创建 <a> 的方式唤起浏览器的下载
